# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2026 Hadi Chokr <hadichokr@icloud.com>
[App]
Id=org.kde.kjar
Name=Java Support
Icon=application-x-java-archive

[Remote]
Name=kjar-nightly
Url=https://cdn.kde.org/flatpak/kjar-nightly/kjar-nightly.flatpakrepo

[Install]
PostInstall=flatpak run org.kde.kjar --generate-wrappers
